# Following both images are served by dockerhub themselves.
#FROM debian:stretch-slim
#FROM debian:stretch AS runner

# But currently I prefer bitnami deb image
FROM bitnami/minideb-extras-base:stretch-r260
LABEL maintainer "Bitnami <containers@bitnami.com>"


